In [37]:
import tqdm
import time
import numpy as np
import pandas as pd
from geopy.geocoders import Nominatim

In [2]:
geolocator = Nominatim(user_agent="Nothing_specific")

In [3]:
location = geolocator.geocode("Verden/Aller")

In [4]:
print((location.latitude, location.longitude))

(52.94106755, 9.235471627440539)

In [31]:
cities = pd.read_csv("cities.csv")

In [11]:
authors = pd.read_csv("authors_final.csv")

In [26]:
birth_places = authors.birth_place.unique().tolist()

In [32]:
living_places = cities.city.unique().tolist()

In [33]:
places = birth_places + living_places

In [46]:
places = set(places)
places = list(places)

In [50]:
cleaned_places = [x for x in places if str(x) != 'nan']

cleaned_places.sort()

cleaned_places

In [56]:
latitudes = []
longitudes = []
for i, place in tqdm.tqdm(enumerate(cleaned_places)):
    time.sleep(1)
    location = geolocator.geocode(place)
    if location != None:
        latitudes.append(location.latitude)
        longitudes.append(location.longitude)
    else:
        latitudes.append(np.nan)
        longitudes.append(np.nan)

253it [04:24,  1.04s/it]

In [70]:
cities_geodata = pd.DataFrame({"city": cleaned_places, "lat": latitudes, "lon": longitudes, "distance": distances})

In [71]:
cities_geodata

                      city        lat        lon  distance
0                   Aachen  50.776351   6.083862     760.0
1                    Aarau  47.392715   8.044445     483.0
2                    Adnet  47.696357  13.130757     149.0
3       Adnet bei Salzburg  47.696357  13.130757     149.0
4                Alblingen        NaN        NaN       NaN
..                     ...        ...        ...       ...
248                 Zürich  47.372394   8.542333     446.0
249           am Dachstein  48.560886   7.531900     553.0
250         in Deutschland  51.254489   7.148873     734.0
251  südliches Waldviertel  48.317202  15.203420     200.0
252        Übach-Palenberg  50.921380   6.112870     768.0

[253 rows x 4 columns]

In [72]:
cities_geodata.to_csv("cities_geodata.csv")

In [68]:
from geopy import distance

distances = []
location = geolocator.geocode("Klagenfurt")
klagenfurt = (location.latitude, location.longitude)
for i in range(len(cleaned_places)):
    place = (latitudes[i], longitudes[i])
    if place !=(np.nan, np.nan):
        print(distance.distance(klagenfurt, place).km)
        distances.append(int(distance.distance(klagenfurt, place).km))
    else:
        print(np.nan)
        distances.append(np.nan)

760.716059313334
483.79721431446285
149.035857097654
149.035857097654
nan
nan
601.9018674242712
nan
860.8157522802285
933.4112672095804
nan
309.2755189233156
766.4160724618954
580.143240496478
584.7954951737327
861.8147532239543
571.0268531254718
513.3662446512253
930.7970210320345
443.3398913187438
1131.9402936097672
520.5513129444713
894.0703698310992
658.9059435222171
524.6414102875717
1228.8199374809114
541.325010437906
732.0005204260435
747.9647790000427
330.99213706330124
6460.732129859889
520.924102748007
235.7093124770738
684.628281323622
359.9388024759936
818.98042257329
6767.80166830705
471.37668678529025
317.0565922215979
438.21999555798834
341.28840349713823
194.73225728060982
709.7187588905043
7406.053224621393
570.9647590381023
813.7948300376734
900.1077305249212
358.0217901065628
nan
1645.8451057408995
739.4417782084971
752.0390098755986
245.79556054010752
451.7579423046132
721.5915213427162
540.771752758281
412.21406969300375
412.79886607080266
639.9724640588389
1658.2467328447053
443.18064805442964
308.64091045334345
398.5650781689073
397.49376402671504
567.4211604080025
423.69924341863515
511.49386633779375
385.070580049548
261.9436089915522
628.9530972635399
605.3615104561677
281.69879327240324
398.7931257598148
119.67386636396293
99.56548762399935
490.3815687848171
655.7297644402709
632.3580279904688
222.12969136563174
566.7328398994972
828.6232504644188
707.4165077602503
799.0891766805281
719.9077155996762
520.6901885950947
374.19918112002284
853.8532816423416
894.7761070716715
511.8006075897945
538.9872903425515
71.818051917922
439.73076232783967
282.23316719442175
691.2297185735353
9113.361575606688
360.79533028334356
618.465751459718
721.5243265125883
819.043837552435
752.6343820383021
575.7252016194294
nan
242.56927816127788
594.9456847815391
192.42279506630464
233.1456400119736
1740.7689405251037
806.0984685193305
716.4020383364743
515.3461243377941
629.4978716313082
1825.6754433564306
905.8814362705397
445.19650330497626
0.0
240.971717393639
405.959123057157
462.0178267640839
907.9641832916528
110.92338630451499
721.8283190896747
251.92048156263385
484.30271148746033
552.3385428333188
636.674821545115
614.099168371662
696.597178649836
399.91152646928117
543.3607696085384
122.05911890254626
103.32431197503291
nan
187.13312671572635
709.9625736586255
512.8943491301812
1183.708888250196
9888.915141383337
603.9325016435448
460.2613934560374
743.3211762528209
499.6875217390918
583.8746244924529
618.2860876311469
220.77454097359282
455.7758180294314
436.25473137869835
760.2499454612139
531.5411821058469
11448.934647696047
885.5266047766706
263.178578648573
768.3591199349571
266.2873084071187
264.0009885670855
766.7830019674994
821.4514936752369
363.997591374218
529.5993785786605
155.14879961419825
508.522110232666
489.44993867852634
9159.66938814504
1150.7151297891637
396.3145471028195
547.028855667358
524.2405564217476
581.1116595763272
1257.841707235752
773.9673960613154
833.9771118647178
255.9020375484039
929.3830068549698
214.26332043171016
489.90616664608655
39.234715688359394
598.3042645992783
648.9439869314662
511.94862334695887
708.7857774202254
152.75352601408215
586.1338734785855
272.15450926486386
363.22297961943724
371.06497421924166
516.5057998391327
845.1294096281869
494.24412456526284
683.5370105460058
618.3729504269884
161.87881065689157
9965.108799927477
191.25963278918803
700.8373255862351
593.4884137800885
nan
464.89824915049394
806.1029679562361
643.0321716419006
687.7498851248782
474.5010174470902
246.1783041307363
731.7658139928407
385.2819985279646
43.059413555189714
1046.7308945481036
975.643744081757
157.67198890137215
538.9265387119634
95.57690150963442
453.25863445151066
17.770388061219762
67.59600781894956
2378.3643838960634
919.7530499320025
372.44159963403575
220.41421008204614
11070.060010447904
448.13680546976195
434.11962491026367
483.5652957710417
477.35147321034907
432.7986424724522
290.65808766578095
201.75361410096306
791.5512545994156
35.081383646023404
498.6692670559098
806.4572536250869
616.4443500654402
151.33876972966385
192.49593067023386
838.7495968946923
350.1552560618181
377.0352851606501
495.6077178088921
716.2333923770507
nan
860.6297826532614
235.24240248986607
591.3604649536627
635.4342063721101
484.20917856177925
693.19705676875
359.0329663751465
828.9995096597951
733.6610419098441
740.605551128705
503.1286765507323
446.2664450000164
553.0701646947147
734.4710699656263
200.1077849442408
768.2327402827707

In [69]:
distances

[760,
 483,
 149,
 149,
 nan,
 nan,
 601,
 nan,
 860,
 933,
 nan,
 309,
 766,
 580,
 584,
 861,
 571,
 513,
 930,
 443,
 1131,
 520,
 894,
 658,
 524,
 1228,
 541,
 732,
 747,
 330,
 6460,
 520,
 235,
 684,
 359,
 818,
 6767,
 471,
 317,
 438,
 341,
 194,
 709,
 7406,
 570,
 813,
 900,
 358,
 nan,
 1645,
 739,
 752,
 245,
 451,
 721,
 540,
 412,
 412,
 639,
 1658,
 443,
 308,
 398,
 397,
 567,
 423,
 511,
 385,
 261,
 628,
 605,
 281,
 398,
 119,
 99,
 490,
 655,
 632,
 222,
 566,
 828,
 707,
 799,
 719,
 520,
 374,
 853,
 894,
 511,
 538,
 71,
 439,
 282,
 691,
 9113,
 360,
 618,
 721,
 819,
 752,
 575,
 nan,
 242,
 594,
 192,
 233,
 1740,
 806,
 716,
 515,
 629,
 1825,
 905,
 445,
 0,
 240,
 405,
 462,
 907,
 110,
 721,
 251,
 484,
 552,
 636,
 614,
 696,
 399,
 543,
 122,
 103,
 nan,
 187,
 709,
 512,
 1183,
 9888,
 603,
 460,
 743,
 499,
 583,
 618,
 220,
 455,
 436,
 760,
 531,
 11448,
 885,
 263,
 768,
 266,
 264,
 766,
 821,
 363,
 529,
 155,
 508,
 489,
 9159,
 1150,
 396,
 547,
 524,
 581,
 1257,
 773,
 833,
 255,
 929,
 214,
 489,
 39,
 598,
 648,
 511,
 708,
 152,
 586,
 272,
 363,
 371,
 516,
 845,
 494,
 683,
 618,
 161,
 9965,
 191,
 700,
 593,
 nan,
 464,
 806,
 643,
 687,
 474,
 246,
 731,
 385,
 43,
 1046,
 975,
 157,
 538,
 95,
 453,
 17,
 67,
 2378,
 919,
 372,
 220,
 11070,
 448,
 434,
 483,
 477,
 432,
 290,
 201,
 791,
 35,
 498,
 806,
 616,
 151,
 192,
 838,
 350,
 377,
 495,
 716,
 nan,
 860,
 235,
 591,
 635,
 484,
 693,
 359,
 828,
 733,
 740,
 503,
 446,
 553,
 734,
 200,
 768]